name: Release Rust Package

on:
  push:
    tags:
      - 'rust-v*'

permissions:
  contents: write

jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
          working-directory: packages/metro-mdp-rust
          manylinux: auto
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: wheels-linux-${{ matrix.target }}
          path: packages/metro-mdp-rust/dist

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Build wheel
        uses: PyO3/maturin-action@v1
        with:
          target: aarch64
          args: --release --out dist --find-interpreter
          working-directory: packages/metro-mdp-rust
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: wheels-macos-aarch64
          path: packages/metro-mdp-rust/dist

  release:
    runs-on: ubuntu-latest
    needs: [linux, macos]
    steps:
      - uses: actions/download-artifact@v6
        with:
          path: wheels
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: wheels/**/*
          body: |
            rust-powered python package

            install:
            ```bash
            pip install git+https://github.com/${{ github.repository }}.git@${{ github.ref_name }}#subdirectory=packages/metro-mdp-rust
            ```
