name: release python lib

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: build package
        run: |
          pip install build hatchling
          cd packages/metro-mdp-lib
          python -m build

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: packages/metro-mdp-lib/dist/*
          body: |
            python package release

            install:
            ```bash
            pip install git+https://github.com/${{ github.repository }}.git@${{ github.ref_name }}#subdirectory=packages/metro-mdp-lib
            ```
